#!/usr/bin/env bash
alias ka="killall"
alias mkd="mkdir -pv"
alias mpv='mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)'
alias calcurse="calcurse -D ~/.config/calcurse"
alias f='$FILE'
alias g="git"
alias pgl="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
alias e='$EDITOR'
alias x="sxiv -ft *"
alias ls="ls -hA --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ccat="highlight --out-format=ansi"
alias yt="youtube-dl -i -o '%(upload_date)s-%(title)s.%(ext)s'"
alias yta="yt -x -f bestaudio/best"
alias YT="youtube-viewer -C"
alias lsp="yay -Qett --color=always | less"
alias ffmpeg="ffmpeg -hide_banner"
alias fuck='sudo $(history -p !!)'
alias dot='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias gbr='git --git-dir=$PWD/.repo --work-tree=$PWD'
alias ghci-core="ghci -ddump-simpl -dsuppress-idinfo -dsuppress-coercions -dsuppress-type-applications -dsuppress-uniques -dsuppress-module-prefixes"
alias gh="gen-hie | tee hie.yaml"
alias web="w3m duckduckgo.com/lite"
alias cp="advcp -g"
alias mv="advmv -g"
alias wine="PULSE_LATENCY_MSEC=60 wine"

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

vf() {
	fzf | xargs -r -I % "$EDITOR" %
}

ignore() {
	gibo dump "$@" > .gitignore
}

transcodeAudio() {
	ffmpeg -i "$1" -vn -ar 44100 -ac 2 -b:a 192k "$2"
}

transcodeVideo() {
	ffmpeg -i "$1" -ar 44100 -ac 2 -b:a 192k "$2"
}

javaver() {
	sudo archlinux-java set "java-$1-openjdk"
}

hdf() {
	last="$(history 1 | cut -d ' ' -f 1)"
	for i in $(seq 1 "$((last - $1 + 2))"); do
		history -d "$1"
	done
}

npup() {
	[ -r "$1" ] || {
		echo "Can't access $1"
		return 1
	}
	curl -F"file=@$1" https://0x0.st
}

IFS=$'\n' read -r -d '' -a __aliases <<< "$(
	alias -p | sed 's/=.*//g' | sed 's/alias //g'
)"
for i in "${__aliases[@]}"; do
	complete -F _complete_alias "$i"
done
