#!/usr/bin/env sh

xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr -s 1920x1080

# Switch to DE with caps to access APL
# setxkbmap -layout de,apl -option grp:caps_switch
# Switch to DE with caps as CTRL
setxkbmap -layout de -option ctrl:nocaps
xrdb ~/.Xresources & # Load X resources
setbg & # Set the background
sxhkd & # Bind keys
# Properties button extra Mod/Escape
xmodmap -e 'keycode 135 = Super_R' &
xset r rate 300 50 & # Speed xrate up
unclutter & # Remove mouse when idle
xcompmgr & # xcompmgr for transparency
dunst & # dunst for notifications
mpdupdate &
calcurse --daemon &

pipewire &
pipewire-media-session &
pipewire-pulse &

# exec emacs
exec i3
